### PR TITLE
Migrate to keying fingerprints by workspace

### PR DESCRIPTION
**Pull request by whostolebenfrog**
jess: This has Ben's changes to DDL and also some additional ones
And integration tests so we can test the SQL
And changes to lots of SQL
And removal of some SQL that wasn't used
And removal of the ability to say workspaceId = "*" and get all of them.

### CODE REVIEW

**Comment by cdupuis** [comment]
@jessitron can this PR please be rebased to solve the merge conflict?

**Comment by cdupuis** [comment]
Nevermind @jessitron, I went ahead and rebased this PR.

**Review by cdupuis — APPROVED** [review]
LGTM

**Comment by dalvizu** [comment]
This breaks the `atomist analyze local repositories` command:

`Error: null value in column "workspace_id" violates not-null constraint`

**Comment by dalvizu** [comment]
It looks like `org-visualizer` docker image (https://hub.docker.com/layers/atomist/org-visualizer/latest/images/sha256-88b09d93c93aeae45412d08c7de538cb440c3e2a834e09eaff0bc49da4f67b6c) does not have this change, but if it were to be rebuilt, it would pick up this change and the new DDL would reproduce the error

**Pull request merged**
